import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Header } from '@/components/Header/Header'
import NewResource from '@/components/NewResource'
import { auth } from "@/auth"
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'LangComprehend',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await auth()

  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        {/* <SessionProvider session={session}> */}
        <div className='h-screen flex-col flex'>
          <Header />
          {children}
          {session?.user?.email && <NewResource email={session.user.email} />}
        </div>
        <Toaster />
        {/* </SessionProvider> */}
      </body>
    </html>
  )
}
