import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Nav from './components/Nav'

import SessionProvider from './components/SessionProvider'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'LangComprehend',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        {/* <SessionProvider session={session}> */}
        <div className='h-screen flex-col flex'>
          <Nav />
          {children}
        </div>
        {/* </SessionProvider> */}
      </body>
    </html>
  )
}
