POST http://localhost:3000/api/text
Content-Type: application/json

{
  "text": "Hello World!",
  "n_questions": 1,
  "language": "en",
  "url": "https://www.google.com",
  "questions": [],
  "answers": [],
  "vocab": [],
  "topics": [],
  "entities": []
}