name: Fast API docker build push

on:
  push:
    branches: ["main", "vocab-trainer-feature-branch"]
  pull_request:
    branches: ["main", "vocab-trainer-feature-branch"]

permissions:
  contents: read

jobs:
  
  test_api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api_backend/requirements.txt
      - name: Run tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          VOC_COLL_NAME: vocabs
          DB_NAME: test
          MONGO_URI: ${{ secrets.MONGO_URI }}

        run: python -m pytest

  build_api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build docker image for FastAPI
        run: docker build -t laurin_brechter/fastapi-docker:0.0.1 ./api_backend
      